export { BadgeSprite } from "./BadgeSprite";
export { BadgeIcon } from "./BadgeIcon";
export { BadgeCard } from "./BadgeCard";
export { BADGE_IDS } from "./badgeIds";
export { BADGE_META } from "./badgeMeta";
export { getEarnedBadges } from "./badgeLogic";
export { toUserStatsFromQuizResult } from "./quizBadgeAdapter";
export type { BadgeId } from "./badgeIds";
export type { BadgeMeta, BadgeGroup } from "./badgeMeta";
export type { UserStats } from "./badgeLogic";